# Copyright (c) Facebook, Inc. and its affiliates.
#



name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up CI directory
        working-directory: ${{github.workspace}}
        run: |
          echo "implement in the future"
          pwd
          ls

      - uses: actions/checkout@v3

      - name: install environment
        run: |
          # cat /proc/cpuinfo && cat /proc/meminfo && df -h
          # pwd && ls
          git branch
          git fetch
          git branch
          # export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install --no-install-recommends -y clang-format-12 python3-pip git make ssh
          echo "-----------------------------------------------------------------1"
          pip3 install cmake_format black regex
          echo "-----------------------------------------------------------------2"
          
          # pip3 cache purge

          sudo apt purge --auto-remove -y python3-pip
          sudo update-alternatives --install /usr/bin/clang-format clang-format "$(command -v clang-format-12)" 12
          sudo apt clean
      
      - name: format-check
        run: |
          git fetch --recurse-submodules=no origin main ${{github.event.pull_request.base.sha}}
          git branch
          cat .github/workflows/check.yml
          if ! make format-check; then
            make format-fix
            echo -e "\n==== Apply using:"
            echo "patch -p1 \<<EOF"
            git --no-pager diff
            echo "EOF"
            false
          fi

      - name: header-check
        run: |
          git fetch --recurse-submodules=no origin main ${{github.event.pull_request.base.sha}}
          if ! make header-check; then
            make header-fix
            echo -e "\n==== Apply using:"
            echo "patch -p1 \<<EOF"
            git --no-pager diff
            echo "EOF"
            false
          fi